sudo: required
services:
  - docker

before_install:
  - docker build -t lwndev/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lwndev/react-test npm test

after_success:
 - docker build -t lwndev/multi-client ./client
 - docker build -t lwndev/multi-nginx ./nginx
 - docker build -t lwndev/multi-server ./server
 - docker build -t lwndev/multi-worker ./worker
# Log in to the docker CLI 
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Push images to Docker Hub
 - docker push lwndev/multi-client
 - docker push lwndev/multi-nginx 
 - docker push lwndev/multi-server
 - docker push lwndev/multi-worker